# Generated by Django 5.2.4 on 2025-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0004_alter_booking_date_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
