# Generated by Django 5.2.4 on 2025-07-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0006_alter_booking_date_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
