# Generated by Django 5.2.4 on 2025-07-16 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0008_alter_profile_age_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2025, 7, 16)),
        ),
    ]
