# Generated by Django 5.2.4 on 2025-07-20 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0010_booking_duration_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2025, 7, 20)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailylimit',
            name='limit',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
